name: Test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x.x'
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
        env:
          TENOR_TEST_API_KEY: ${{ secrets.TENOR_TEST_API_KEY }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()                               # run this step even if previous step failed
        with:
          name: DotNet Tests                                     # Name of the check run which will be created
          path: TenorSharp.Tests/TestResults/test-results.trx    # Path to test results
          reporter: dotnet-trx                                   # Format of test results
          